export const GIBERNE_BOOKS = [
  {
    id: 17,
    title: "La Vertu cardinale",
    author: "Vivien Destro",
    keywords: ["roman", "politique", "société", "française", "spiritualité"],
    url: "https://www.lagiberne.fr/books/17",
    cover: "https://www.lagiberne.fr/storage/books/W0BQbLJvIPIqgX5loed0aTuuJqUT7GCISmn40cXj.jpg",
  },
  {
    id: 16,
    title: "Légion",
    author: "Victor di Donatelis",
    keywords: ["roman historique", "guerre", "histoire", "psychologie", "transgression"],
    url: "https://www.lagiberne.fr/books/16",
    cover: "https://www.lagiberne.fr/storage/books/KrYuVI5FplPTUmIze2j9N3ddOXdjgQWe5tujZIC3.jpg",
  },
  {
    id: 15,
    title: "Araldus",
    author: "David Pascaud",
    keywords: ["roman historique", "moyen âge", "aventure", "politique", "héroïsme"],
    url: "https://www.lagiberne.fr/books/15",
    cover: "https://www.lagiberne.fr/storage/books/AbCchS8HzHdhUNEVMjemRWeNYtjpEs80Aijm3Bg7.jpg",
  },
  {
    id: 14,
    title: "Rouler sous les étoiles",
    author: "Paul Ginabat",
    keywords: ["voyage", "aventure", "européenne", "spiritualité", "témoignage"],
    url: "https://www.lagiberne.fr/books/14",
    cover: "https://www.lagiberne.fr/storage/books/b1cJff071JQBdnLXHbyYXJP3630ltwxnmPiuXbzD.jpg",
  },
  {
    id: 13,
    title: "La Grâce de Barbara",
    author: "Manon Petiot",
    keywords: ["roman", "société", "amour", "psychologie", "américaine"],
    url: "https://www.lagiberne.fr/books/13",
    cover: "https://www.lagiberne.fr/storage/books/zMF1bhv3xpzishM83DLRgd0h619pCxOkZ1n6aqcF.jpg",
  },
  {
    id: 9,
    title: "Les Contrefaits",
    author: "Alexandre Jordeczki",
    keywords: ["satire", "littérature", "société", "humour", "roman"],
    url: "https://www.lagiberne.fr/books/9",
    cover: "https://www.lagiberne.fr/storage/books/Jordeczki_Contrefaits_couv_1.jpg",
  },
  {
    id: 8,
    title: "Rolf",
    author: "Victor di Donatelis",
    keywords: ["fantastique", "psychologie", "horreur", "mystère", "roman"],
    url: "https://www.lagiberne.fr/books/8",
    cover: "https://www.lagiberne.fr/storage/books/Rolf_cov_1.jpg",
  },
  {
    id: 7,
    title: "Objectif 23",
    author: "Aurélien Chrétien",
    keywords: ["dystopie", "science-fiction", "politique", "société", "transgression"],
    url: "https://www.lagiberne.fr/books/7",
    cover: "https://www.lagiberne.fr/storage/books/Objectif23_C1.jpg",
  },
  {
    id: 6,
    title: "Les Bibliophiles",
    author: "Mathias Kessler",
    keywords: ["littérature", "satire", "société", "humour", "roman"],
    url: "https://www.lagiberne.fr/books/6",
    cover: "https://www.lagiberne.fr/storage/books/9782959372018_cov_1.jpg",
  },
  {
    id: 5,
    title: "L’Hydre jamais ne faiblit",
    author: "Antoine Zwicky",
    keywords: ["fantasy", "guerre", "aventure", "politique", "héroïsme"],
    url: "https://www.lagiberne.fr/books/5",
    cover: "https://www.lagiberne.fr/storage/books/L_Hydre_2_C1.jpg",
  },
  {
    id: 4,
    title: "Les Noces de terre",
    author: "Xie Feile",
    keywords: ["roman historique", "guerre", "histoire", "horreur", "psychologie"],
    url: "https://www.lagiberne.fr/books/4",
    cover: "https://www.lagiberne.fr/storage/books/FEILE_Noces_couv_1.jpg",
  },
  {
    id: 3,
    title: "L’Hydre jamais ne meurt",
    author: "Antoine Zwicky",
    keywords: ["fantasy", "guerre", "aventure", "politique", "héroïsme"],
    url: "https://www.lagiberne.fr/books/3",
    cover: "https://www.lagiberne.fr/storage/books/l_hydre_jamais_ne_meurt_C1.jpg",
  },
  {
    id: 2,
    title: "Les Sains d’esprit",
    author: "Jules Lacroix",
    keywords: ["roman", "psychologie", "société", "amour", "transgression"],
    url: "https://www.lagiberne.fr/books/2",
    cover: "https://www.lagiberne.fr/storage/books/les_sains_d_esprit_C1.jpg",
  },
  {
    id: 1,
    title: "Pays Réels",
    author: "Mathias Kessler",
    keywords: ["dystopie", "politique", "société", "guerre", "roman"],
    url: "https://www.lagiberne.fr/books/1",
    cover: "https://www.lagiberne.fr/storage/books/pays_reels_C1.jpg",
  },
  {
    id: 12,
    title: "L’Art d’écrire",
    author: "Antoine Albalat",
    keywords: ["écriture", "essai", "littérature", "langue", "classique"],
    url: "https://www.lagiberne.fr/books/12",
    cover: "https://www.lagiberne.fr/storage/books/L_art_d_ecrire_C1.jpg",
  },
  {
    id: 11,
    title: "Ballades des frontières écossaises",
    author: "Walter Scott",
    keywords: ["poésie", "aventure", "mythologie", "britannique", "classique"],
    url: "https://www.lagiberne.fr/books/11",
    cover: "https://www.lagiberne.fr/storage/books/Ballades_des_frontieres_ecossaises_C1.jpg",
  },
  {
    id: 10,
    title: "Les Héros",
    author: "Thomas Carlyle",
    keywords: ["essai", "histoire", "héroïsme", "philosophie", "classique"],
    url: "https://www.lagiberne.fr/books/10",
    cover: "https://www.lagiberne.fr/storage/books/Les_heros_C1.jpg",
  },
];
